#Project info 
site_name: Amadeus for Developers
site_url: https://developers.amadeus.com
site_description: Amadeus for Developers Self-Service APIs Documentation
site_author: Amadeus for Developers

#Repository
repo_name: amadeus4dev/developer-guides
repo_url: https://github.com/amadeus4dev/developer-guides

#Copyright
copyright: Copyright Â© Amadeus IT Group S.A.

#Configuration 
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes 
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Amadeus
    code: Source Sans Pro
  favicon: assets/favicon.ico
  logo: assets/logo.svg

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - git-revision-date-localized
  - mkdocs-video

#Customization
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-Z1Z88HQZR9
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: -1
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our feedback form</a>.  
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amadeus4dev
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/cVrFBqx
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/amadeus4dev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/showcase/amadeus-for-developers

#Additional CSS
extra_css:
  - stylesheets/extra.css

#Page tree
nav:
    - Home: index.md
    - Quick Start: quick-start.md
    - Pricing: pricing.md
    - Free Test Data Collection: test-data.md
    - API Keys:
       - Authorization: API-Keys/authorization.md
       - Production: API-Keys/moving-to-production.md
    - Rate Limits: api-rate-limits.md
    - Pagination: pagination.md
    - Common Errors: common-errors.md
    - API Tutorials:
        - Covid-19 & travel Safety: resources/covid-19.md
        - Flights: resources/flights.md
        - Hotels: resources/hotels.md
        - Destination experiences: resources/destination-experiences.md
        - Itinerary management: resources/itinerary-managment.md
        - Market insights: resources/market-insight.md
    - SDK Tutorials:
        - Amadeus SDK overview: sdks/sdk-overview.md
        - Node SDK: sdks/node-sdk.md
        - Python SDK: sdks/python-sdk.md
        - Java SDK: sdks/java-sdk.md
        - Using OpenAPI Generator: sdks/openapi-generator.md
    - Examples and Prototypes:
        - Code examples: examples/code-example.md
        - Prototypes: examples/prototypes.md
    - FAQ: faq.md 
    - Migration guides:
        - Hotel search: migration-guides/hotel-search.md
        - Travel restrictions: migration-guides/travel-restrictions.md