theme:
  name: null
  custom_dir: 'material'
  highlightjs: true
  logo: assets/logo.png

  language: en
  icon:
    logo: logo

  features:
    - foo

  # 404 page
  static_templates:
    - 404.html

  font:
    text: Amadeus
    code: Source Sans Pro

  favicon: icons/favicon.ico

  palette:
    scheme: default
    primary: blue
    accent: blue

  include_search_page: false
  search_index_only: true

markdown_extensions:
  - admonition
  - meta
  - codehilite:
      linenums: true
  - pymdownx.tabbed
  - pymdownx.superfences

plugins:
  - search
  - git-revision-date-localized

extra_css:
  - css/amadeus.css

site_name: Amadeus for Developers
site_url: https://developers.amadeus.com
site_description: Amadeus for Developers Documentation
site_author: Amadeus for Developers

repo_name: amadeus4dev/developer-guides
repo_url: https://github.com/amadeus4dev/developer-guides

copyright: Copyright Â© Amadeus IT Group S.A.

nav:
    - Home: index.md
    - Getting Started:
        - Making your first API call: get-started/first-api-call.md
        - Pricing: get-started/pricing.md
        - Self-Service vs Enterprise: get-started/self-service-enterprise.md
        - Moving to Production: get-started/moving-to-production.md
    - API General:
        - Authorization: guides/authorization.md
        - Common errors: guides/permissions-and-errors.md
        - Pagination: guides/pagination.md
        - Rate Limits: guides/api-rate-limits.md
        - Test Data Collection: guides/api-data-collection.md
    - API Tutorials:
        - Covid-19 & Travel Safety: resources/covid-19.md
        - Flights: resources/flights.md
        - Hotels: resources/hotels.md
        - Destination experiences: resources/destination-experiences.md
        - Itinerary management: resources/itinerary-managment.md
        - Market Insights: resources/market-insight.md
        - Locations (to be merged): resources/locations.md
        - Predictions(to be merged): resources/predictions.md
    - Tooling:
        - Node SDK: sdks/node-sdk.md
        - Python SDK: sdks/python-sdk.md
        - Java SDK: sdks/java-sdk.md
        - .NET SDK: sdks/dotnet-sdk.md
        - Ruby SDK: sdks/ruby-sdk.md
        - iOS SDK: sdks/ios-sdk.md
        - Android SDK: sdks/android-sdk.md
        - OpenAPI Specification: sdks/specification.md
    - Code Examples:
        - Code Examples: examples/code-example.md
        - Prototypes: examples/prototypes.md
    

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amadeus4dev
    - icon: fontawesome/brands/discord
      link: https://discord.gg/UjXwf4F
