theme:
  name: null
  custom_dir: 'material'
  highlightjs: true
  logo: assets/logo.svg

  language: en
  icon:
    logo: logo

  features:
    - foo

  # 404 page
  static_templates:
    - 404.html

  font:
    text: Amadeus
    code: Source Sans Pro

  favicon: icons/favicon.ico

  palette:
    scheme: default
    primary: blue
    accent: blue

  include_search_page: false
  search_index_only: true

markdown_extensions:
  - admonition
  - meta
  - codehilite:
      linenums: true
  - pymdownx.tabbed
  - pymdownx.superfences

plugins:
  - search
  - git-revision-date-localized

extra_css:
  - css/amadeus.css

site_name: Amadeus for Developers
site_url: https://developers.amadeus.com
site_description: Amadeus for Developers Documentation
site_author: Amadeus for Developers

repo_name: amadeus4dev/developer-guides
repo_url: https://github.com/amadeus4dev/developer-guides

copyright: Copyright Â© Amadeus IT Group S.A.

nav:
    - Home: index.md
    - Quick Start: quick-start.md
    - Pricing: pricing.md
    - Free Test Data Collection: test-data.md
    - API Keys:
       - Authorization: API-Keys/authorization.md
       - Production: API-Keys/moving-to-production.md
    - Rate Limits: api-rate-limits.md
    - Pagination: pagination.md
    - Common Errors: common-errors.md
    - API Tutorials:
        - Covid-19 & travel Safety: resources/covid-19.md
        - Flights: resources/flights.md
        - Hotels: resources/hotels.md
        - Destination experiences: resources/destination-experiences.md
        - Itinerary management: resources/itinerary-managment.md
        - Market insights: resources/market-insight.md
    - SDK Tutorials:
        - Amadeus SDK overview: sdks/sdk-overview.md
        - Node SDK: sdks/node-sdk.md
        - Python SDK: sdks/python-sdk.md
        - Java SDK: sdks/java-sdk.md
        - Using OpenAPI Generator: sdks/openapi-generator.md
    - Examples and Prototypes:
        - Code examples: examples/code-example.md
        - Prototypes: examples/prototypes.md
    - FAQ: faq.md 
    

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amadeus4dev
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/cVrFBqx
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/amadeus4dev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/showcase/amadeus-for-developers
  analytics:
    provider: google
    property: G-4BPFT57T5Z
